---

docker_registry: 'registry.jetio.net'
registry_user: 'lianghuiyuan'
registry_pwd: 'Qaz@1234'
ansible_become: yes
ansible_become_method: sudo
ansible_become_password: "Qaz@1234"

cpu_arch: "{{ (ansible_architecture | lower | 
              replace('i386', '386') | 
              replace('x86_64', 'amd64') | 
              replace('aarch64', 'arm64') | 
              replace('armv7l', 'armv7') | 
              replace('armv6l', 'armv6')) if ansible_architecture is defined else '' }}"
image_archive_dir: '/tmp/images'
# hagroup_id: 3
# fluentbit_src_path: ../../../fluentbit
# fluentbit_dest_path: /opt/fluentbit
# jetmon_server_src_path: ../../../jetmon-server
# jetmon_server_dest_path: /opt/jetmon-server
# exporters_src_path: ../../../exporters
# exporters_dest_path: /opt/exporters