nats_version: "0.25.6"
nats_image: 'nats-streaming'
nats_image_archive_name: 'nats_{{ nats_version }}.tar'

stan_http_port: '4222'
stan_report_port: '8222'
stan_cluster_port: '6222'
stan_data_dir: '/mnt/nats/data'
stan_config_dir: '/mnt/nats/config'