name: Molecule

on:
  push:
    branches:
      - master
      - release/v*
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: 'sleighzy.zookeeper'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'sleighzy.zookeeper'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible docker "molecule-plugins[docker]"

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
