docker_kafka:
  hosts:
    node10203:
      ansible_host: 192.168.10.203
      ansible_ssh_user: root
      ansible_ssh_pass: jetio
    node10204:
      ansible_host: 192.168.10.204
      ansible_ssh_user: root
      ansible_ssh_pass: jetio
    node10205:
      ansible_host: 192.168.10.205
      ansible_ssh_user: root
      ansible_ssh_pass: jetio
docker_fluentbit:
  hosts:
    node10203:
      ansible_host: 192.168.1.63
      ansible_ssh_user: root
      ansible_ssh_pass: jetio
docker_elasticsearch:
  hosts:
    es_datanode_01:
      ansible_host: 116.63.88.24
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
    es_datanode_02:
      ansible_host: 124.71.32.133
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
    es_datanode_03:
      ansible_host: 218.245.96.170
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
docker_kibana:
  hosts:
    es_datanode_01:
      ansible_host: 116.63.88.24
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
docker_logstash:
  hosts:
    es_datanode_02:
      ansible_host: 124.71.32.133
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
docker_postgresql:
  hosts:
    es_datanode_01:
      ansible_host: 116.63.88.24
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
docker_redis:
  hosts:
    es_datanode_01:
      ansible_host: 116.63.88.24
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
    es_datanode_02:
      ansible_host: 124.71.32.133
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
docker_nats:
  hosts:
    es_datanode_03:
      ansible_host: 218.245.96.170
      ansible_ssh_user: root
      ansible_ssh_pass: Mec@CloudEdge2023
test:
  hosts:
    node548:
      ansible_host: 192.168.5.48
      ansible_ssh_user: root
      ansible_ssh_pass: jetio
    node549:
      ansible_host: 192.168.5.49
      ansible_ssh_user: root
      ansible_ssh_pass: jetio
    node550:
      ansible_host: 192.168.5.50
      ansible_ssh_user: root
      ansible_ssh_pass: jetio
