---
# install, uninstall, start, stop, restart     #/upgrade/update

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "started"
    docker_container_restart: false
  tags: ['install', 'start']

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "stopped"
    docker_container_restart: false
  tags: ['stop']

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "started"
    docker_container_restart: true
  tags: ['restart']

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "absent"
    docker_container_restart: false
  tags: ['uninstall']

# - name: main | login dockerhub, pull latest image and delete the expired image
#   import_tasks: image.yml

# - name: main | deploy kafka with docker
#   import_tasks: container.yml


- name: debug vault 
  debug:
    msg: "Docker registry: {{ docker_registry }}, User: {{ registry_user }}, Password: {{ registry_pwd }}"
  tags: ['always']
