- name: service | init kafka service with create topics if needed
  block:
  - name: Check and create Kafka topic if it does not exist
    shell: |
      if ! docker exec kafka_{{ kafka_broker_id }} kafka-topics.sh --list \
          --bootstrap-server {{ kafka_service_ip }}:{{ kafka_host_broker_port }} | grep -w {{ item.name }}; then
        docker exec kafka_{{ kafka_broker_id }} kafka-topics.sh --create --topic {{ item.name }} \
          --bootstrap-server {{ kafka_service_ip }}:{{ kafka_host_broker_port }} \
          --partitions {{ item.partitions }} --replication-factor {{ item.replication_factor }};
      fi
    ignore_errors: true
    changed_when: false
    failed_when: false
    loop: "{{ kafka_topics }}"
    loop_control:
      loop_var: item
    tags: ['install']