---

version: "{{ '3.4_' + (cpu_arch | lower) }}"
image: 'registry.jetio.net/library/bitnami/kafka'
image_archive_name: 'kafka_{{ version }}.tar'

# vip: '10.162.100.127'
# kafka_cluster_id: 'jetio_kafka_cluster'
kafka_cluster_id: '4L6g3nShT-eMCtK--X86sw'
topics:
  - name: 'bucket-log'         # for logmanager
    partitions: 13
    replication_factor: 1

kafka_home_dir: /mnt/kafka
# kafka_shell_dir: /opt/kafka/bin
# kafka_config_dir: /opt/kafka/config
# kafka_log_dir: /var/log/kafka
# kafka_data_dir: /mnt/kafka

# container_shell_dir: /opt/kafka/bin
# container_config_dir: /opt/kafka/config
# container_log_dir: /tmp/kraft-combined-logs
# container_data_dir: /var/lib/kafka