---
- name: Converge
  hosts: all
  roles:
    - sleighzy.zookeeper

  tasks:
    - name: 'Test Kafka role'
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
