- name: Verify
  hosts: all

  tasks:
    - name: Get users
      ansible.builtin.getent:
        database: passwd

    - name: Get groups
      ansible.builtin.getent:
        database: group

    - name: Assert that user and group 'kafka' exists
      ansible.builtin.assert:
        that:
          - "'kafka' in getent_passwd"
          - "'kafka' in getent_group"

    - name: Register '/opt/kafka_2.13-3.5.2' installation directory status
      ansible.builtin.stat:
        path: '/opt/kafka_2.13-3.5.2'
      register: install_dir

    - name: Assert that '/opt/kafka_2.13-3.5.2' directory is created
      ansible.builtin.assert:
        that:
          - install_dir.stat.exists
          - install_dir.stat.isdir
          - install_dir.stat.pw_name == 'kafka'
          - install_dir.stat.gr_name == 'kafka'

    - name: Register '/opt/kafka' symlink directory status
      ansible.builtin.stat:
        path: '/opt/kafka'
      register: kafka_dir

    - name: Assert that '/opt/kafka' symlink is created
      ansible.builtin.assert:
        that:
          - kafka_dir.stat.exists
          - kafka_dir.stat.islnk
          - kafka_dir.stat.lnk_target == '/opt/kafka_2.13-3.5.2'

    - name: Register '/var/log/kafka' directory status
      ansible.builtin.stat:
        path: '/var/log/kafka'
      register: kafka_log_dir

    - name: Assert that '/var/log/kafka' directory is created
      ansible.builtin.assert:
        that:
          - kafka_log_dir.stat.exists
          - kafka_log_dir.stat.isdir
          - kafka_log_dir.stat.pw_name == 'kafka'
          - kafka_log_dir.stat.gr_name == 'kafka'

    - name: Register '/opt/kafka/logs' symlink directory status
      ansible.builtin.stat:
        path: '/opt/kafka/logs'
      register: application_logs_symlink

    - name: Assert that '/opt/kafka/logs' symlink is created
      ansible.builtin.assert:
        that:
          - application_logs_symlink.stat.exists
          - application_logs_symlink.stat.islnk
          - application_logs_symlink.stat.lnk_target == '/var/log/kafka'
          - application_logs_symlink.stat.pw_name == 'kafka'
          - application_logs_symlink.stat.gr_name == 'kafka'

    - name: Register '/etc/kafka' directory status
      ansible.builtin.stat:
        path: '/etc/kafka'
      register: config_dir

    - name: Assert that '/etc/kafka' directory is created
      ansible.builtin.assert:
        that:
          - config_dir.stat.exists
          - config_dir.stat.isdir
          - config_dir.stat.pw_name == 'kafka'
          - config_dir.stat.gr_name == 'kafka'

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Assert that Kafka service is installed, running, and enabled
      ansible.builtin.assert:
        that:
          - "'kafka.service' in ansible_facts.services"
          - ansible_facts.services['kafka.service'].state == 'running'
          - ansible_facts.services['kafka.service'].status == 'enabled'
